const ROLE = {
  TYPE: {
    DEFAULT: '1-default',
    CUSTOMIZE: '2-customize',
  }
}

const USER = {
  STATUS: {
    ACTIVE: '1-active',
    INACTIVE: '2-inactive',
  }
}


const ORDER_STATUS_PENDING = 1
const ORDER_STATUS_PROCESSING = 2
const ORDER_STATUS_SHIPPING = 3
const ORDER_STATUS_DELIVERED = 4
const ORDER_STATUS_CANCELLED = 5

const ORDER_STATUS = {
  [ORDER_STATUS_PENDING]: "Chờ xử lý",
  [ORDER_STATUS_PROCESSING]: "Đang xử lý",
  [ORDER_STATUS_SHIPPING]: "Đang giao hàng",
  [ORDER_STATUS_DELIVERED]: "Đã giao hàng",
  [ORDER_STATUS_CANCELLED]: "Đã hủy",
}

const USER_PRIMARY_COLOR = '#27964f'

const SLOGAN = 'Thực phẩm sạch - Cuộc sống xanh'
const WEB_NAME = "Hợp tác xã LAM NGUYỄN (LAM'S FARM)"
const HOSTNAME = "LAMSFARM.COM.VN"

export {
  ROLE,
  USER,
  USER_PRIMARY_COLOR,
  SLOGAN,
  WEB_NAME,
  HOSTNAME,
  ORDER_STATUS,
  ORDER_STATUS_PENDING,
  ORDER_STATUS_PROCESSING,
  ORDER_STATUS_SHIPPING,
  ORDER_STATUS_DELIVERED,
  ORDER_STATUS_CANCELLED
}
